version: '3.7'

services:
    php:
        build:
            context: /var/www/logistique  # Définir le contexte de construction correct
            dockerfile: .docker/php/Dockerfile
        ports:
            - 5173:5173
        volumes:
            - /var/www/logistique:/var/www:cached
        environment:
            - COMPOSER_ALLOW_SUPERUSER=1

    nginx:
        image: nginx
        ports:
            - 8081:80
            - 443:443
        volumes:
            - /var/www/logistique:/var/www
            - /var/www/logistique/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt  # Montez les certificats Let's Encrypt
        depends_on:
            - php

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8082:80
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        volumes:
            - /var/www/logistique/.docker/phpmyadmin/sessions:/sessions

    mail:
        image: axllent/mailpit:latest
        ports:
            - 8025:8025
            - 1025:1025

    db:
        image: mariadb:10.11
        ports:
            - 3307:3306
        volumes:
            - /var/www/logistique/.docker/db/data:/var/lib/mysql
            - /var/www/logistique/.docker/logs:/var/log/mysql
            - /var/www/logistique/.docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - /var/www/logistique/.docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: logistique
            MYSQL_USER: admin
            MYSQL_PASSWORD: 90145781
