services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "81:80"
            - "444:443"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt
        networks:
            - laravel

    db:
        image: mariadb:latest
        container_name: mariadb
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
    server {
    listen 81;
    server_name logistique.nigerdev.com;
    index index.php index.html;
    root /var/www/public;

    client_max_body_size 100M; # 413 Request Entity Too Large

    location / {
    try_files $uri $uri/ /index.php?$query_string;
}

    location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass app:9000;
    fastcgi_read_timeout 3600;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    send_timeout 3600;
    proxy_connect_timeout 3600;
    proxy_read_timeout 3600;
    proxy_send_timeout 3600;
}
}

    server {
    listen 44 ssl;
    server_name logistique.nigerdev.com;

    ssl_certificate /etc/letsencrypt/live/logistique.nigerdev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/logistique.nigerdev.com/privkey.pem;

    root /var/www/public;
    index index.php index.html;

    location / {
    try_files $uri $uri/ /index.php?$query_string;
}

    location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass app:9000;
    fastcgi_read_timeout 3600;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    send_timeout 3600;
    proxy_connect_timeout 3600;
    proxy_read_timeout 3600;
    proxy_send_timeout 3600;
}

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}
